import { svelte } from "@sveltejs/vite-plugin-svelte";
import tailwindcss from "@tailwindcss/vite";
import { defineConfig, loadEnv } from "vite";
import path from "path";
import dfxJson from "./dfx.json" with { type: "json" };
import fs from "fs";
import { fileURLToPath } from "url";
// PWA plugin removed to solve caching issues

const __dirname = import.meta.dirname ?? path.dirname(fileURLToPath(import.meta.url));

// Load environment variables from .env file
const mode = process.env.NODE_ENV || 'development';
const env = loadEnv(mode, process.cwd(), '');

// Use DFX_NETWORK from environment, fallback to 'local'
const dfxNetwork = env.DFX_NETWORK || process.env.DFX_NETWORK || "local";
const isDev = dfxNetwork === "local";
const networkName = dfxNetwork;

type Network = "ic" | "development" | "testing" | "demo" | "prd" | "local";

interface CanisterIds {
  [key: string]: { [key in Network]: string };
}

let canisterIds: CanisterIds = {};
const canisterIdsPath = isDev ? ".dfx/local/canister_ids.json" : "./canister_ids.json";
try {
  canisterIds = JSON.parse(
    fs.readFileSync(canisterIdsPath).toString(),
  );
  console.log(`📋 Loaded canister IDs from: ${canisterIdsPath}`);
  console.log(`🌐 Network: ${networkName}`);
} catch (e) {
  console.error(`\n⚠️  Failed to load canister IDs from ${canisterIdsPath}`);
  console.error("   Before starting the dev server, ensure:");
  console.error("   - For local development: run 'dfx deploy'");
  console.error("   - For network deployment: ensure canister_ids.json exists\n");
}

// List of all aliases for canisters
// This will allow us to: import { canisterName } from "canisters/canisterName"
const aliases = Object.entries(dfxJson.canisters || {}).reduce(
  (acc, [name, _value]) => {
    /* const outputRoot = path.join(
      __dirname,
      ".dfx",
      networkName,
      "canisters",
      name,
    ); */
    const outputRoot = path.join(
      __dirname,
      "src",
      "declarations",
      name,
    );

    return {
      ...acc,
      ["canisters/" + name]: path.join(outputRoot, "index" + ".js"),
    };
  },
  {},
);

// Generate canister ids, required by the generated canister code in .dfx/local/canisters/*
// This strange way of JSON.stringifying the value is required by vite
const canisterDefinitions = Object.entries(canisterIds).reduce(
  (acc, [key, val]) => {
    const canisterId = val[networkName];
    if (!canisterId) {
      console.warn(`⚠️  No canister ID found for '${key}' on network '${networkName}'`);
    }
    return {
      ...acc,
      [`process.env.${key.toUpperCase()}_CANISTER_ID`]: JSON.stringify(canisterId),
      [`process.env.CANISTER_ID_${key.toUpperCase()}`]: JSON.stringify(canisterId),
    };
  },
  {},
);

// PWA removed - no more aggressive caching

// See guide on how to configure Vite at:
// https://vitejs.dev/config/
export default defineConfig({
      plugins: [tailwindcss(), svelte()],
  build: {
    target: "es2020",
    rollupOptions: {
      output: {
        manualChunks(id) {
          if (id.includes("@mlc-ai/web-llm")) return "webllm";
          if (id.includes("@dfinity/")) return "dfinity";
          if (id.includes("html5-qrcode") || id.includes("/qrcode")) return "qr-scanner";
          if (id.includes("svelte-spa-router") || id.includes("@lucide/svelte")) return "ui-libs";
          if (id.includes("/marked")) return "markdown";
        },
      }
    }
  },
  resolve: {
    alias: {
      // Here we tell Vite the "fake" modules that we want to define
      ...aliases,
    },
  },
  //publicDir: "./src/funnai_frontend/public",
  publicDir: "./src/funnai_frontend/assets",
  server: {
    host: true,
    fs: {
      allow: ["."],
    },
    //__________Local vs Mainnet Development____________
    proxy: {
      // This proxies all http requests made to /api to our running dfx instance
      "/api": {
        target: `http://127.0.0.1:4943`,
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/api/, "/api"),
      },
    },
  },
  define: {
    // Here we can define global constants
    // This is required for now because the code generated by dfx relies on process.env being set
    ...canisterDefinitions,
    "process.env.NODE_ENV": JSON.stringify(
      isDev ? "development" : "production",
    ),
    "process.env.DFX_NETWORK": JSON.stringify(dfxNetwork),
    // @dfinity/agent (and other Node-oriented deps) still reference `global`.
    // Vite 8 / the browser do not provide it; always alias to globalThis.
    global: "globalThis",
  },
});